# Generated by Django 3.2.4 on 2021-10-11 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('busbookApp', '0003_auto_20211010_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
    ]
